sudo: required

language: python

env:
  - VER=1.0.0

services:
  - docker

before_install:
  - docker pull cantbewong/mesos-build-module-dev:1.0.0

install:
  - docker build -t travis/mesos-build-module-dvdi-dev:1.0.0 -f Dockerfile-mesos-module-dvdi-dev .
  - docker run -ti -v $TRAVIS_BUILD_DIR/isolator/:/isolator travis/mesos-build-module-dvdi-dev:1.0.0 /bin/bash -c '/usr/bin/make all && cp /isolator/build/.libs/libmesos_dvdi_isolator-${ISOLATOR_VERSION}.so /isolator/'

script:
  - shasum $TRAVIS_BUILD_DIR/isolator/libmesos_dvdi_isolator-${VER}.so